## Docker file to start supporting services for medusa server

version: "3.8"
services:

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker
    volumes:
      - ./docker-volumes/postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      -  "6379:6379"
    restart: always
 
  search:
      image: getmeili/meilisearch
      restart: always
      ports:
        - "7700:7700"
      environment:
        - MEILI_MASTER_KEY=MASTER_KEY
      volumes:
        - ./data/db:/var/lib/postgres:cached
  
 
volumes:
  kafka-volume:
  zookeeper-volume:

  node_modules:
  